### ISSUE TITLE
Failed to run 

### ISSUE THREAD

**Issue by nopattern** [godmanrock/bidirectional-stock-market#1]
Thank you for your code .
      I am a newer to netlogo. I have tested your code The netlogo 6.1.1 failed to convert model. So I download netlogo 5.3.1  and failed to run . The error is as following:
            

> 列表 [2020-02-07 1070.01 1077 1076 1061.02 31278.71 5 0.47 1,047.784 1,064.103 1,082.313 62,387.04 49,334.18 47,810.00] (长度为 14 )中找不到元素 14 .

error while observer running ITEM
  called by procedure INIT-DIVIDENDS (E:\stock\netlogo\bidirectional-stock-market\stockexchange.nls)
  called by procedure SETUP-STOCKS (E:\stock\netlogo\bidirectional-stock-market\stockexchange.nls)
  called by procedure SETUP
  called by 按钮 Setup`

  Have any plan to update or Can I have some advice to run ? Thank you.

**Comment by jihegao** [comment]
It's written in old version of NetLogo. You can try launch it with version 5.3.1.

**Comment by nopattern** [comment]
yes,thank,you!
